<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rwanda</name>
   <tag></tag>
   <elementGuidId>c4438f50-f9e6-4514-935d-31378256a563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
