<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudentManagement</name>
   <tag></tag>
   <elementGuidId>69dfb624-a0af-48d5-8530-f4c9783d3d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='root']/div[2]/aside[1]/div[1]/ul[1]/li[4]/a[1]/span[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
