<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_svg replaced-svg align-middle</name>
   <tag></tag>
   <elementGuidId>2a9e3308-29ed-4394-872c-78ea52eae3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg.replaced-svg.align-middle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6f7f61e2-3ed0-4acf-86a8-e38d28be6a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg replaced-svg align-middle</value>
      <webElementGuid>59766495-a5d4-425c-86df-3c63e95fcfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>8d36853b-f511-49be-a11f-58bd8f78b470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>b87682ca-eeda-4d8c-985f-64ee7b21ec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>19px</value>
      <webElementGuid>91916921-f4c8-4224-9b1c-162dbb4a1ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>21px</value>
      <webElementGuid>a3a71d85-8901-439b-bf95-19cf45c57b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 26 29</value>
      <webElementGuid>a9bf0a08-f290-48f9-b859-7ca2acfdc0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>2a32985f-4d9d-47fd-a4fa-4f283c5565b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-form&quot;)/button[@class=&quot;btn position-absolute search-button search-dictionary&quot;]/svg[@class=&quot;svg replaced-svg align-middle&quot;]</value>
      <webElementGuid>7afca59e-46a8-469e-84f3-9d59298e86ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
